FROM node:18-alpine as development

WORKDIR /app
COPY package.json ./

# We'll run npm install and copy source code when building the actual frontend component
# RUN npm install
# COPY . .

EXPOSE 5173
# CMD ["npm", "run", "dev", "--", "--host"]
CMD ["echo", "Frontend placeholder. Real Vite app will be created soon!"]
